### ISSUE TITLE
pole-arm limitation

### ISSUE THREAD

**Issue by Tux0n0** [WarswordConquestTeam/Warsword-Conquest#17]
i suggest the removal of the slashright/slashleft_polearm tags for any poleaxe/halberd with more than 150 range

**Comment by Tux0n0** [comment]
item IDs:
itm_helhunten_halberd
itm_empire_halberd1/2/3
itm_crusher_halberd1/2/3
itm_orc_halberd
itm_tomb_halberd
itm_house_axe and itm_house_axe2

**Comment by burstonsoftware** [comment]
Switched these item codes from itc_staff to itc_pike
