### ISSUE TITLE
Chaos Dwarf Heavy Shield might need different carry flags

### ISSUE THREAD

**Issue by burstonsoftware** [WarswordConquestTeam/Warsword-Conquest#18]

**Comment by AmkoTheTerrible** [comment]
Changes made to items 756-761
itm_chaos_dwarf_heavy_shield
itm_chaos_dwarf_heavy_shield1
itm_chaos_dwarf_heavy_shield2
itm_chaos_dwarf_heavy_shield3
itm_chaos_dwarf_heavy_shield4
itm_chaos_dwarf_heavy_shield5

changed capabilities: carry_board_shield to carry_round_shield

the change better centers the shield on the back to suit the dimensions of the chaos dwarf heavy shields.

File changed was item_kinds1 using Morghs editor.

[item_kinds1.txt](https://github.com/WarswordConquestTeam/Warsword-Conquest/files/4341145/item_kinds1.txt)

**Comment by burstonsoftware** [comment]
changes made
