### ISSUE TITLE
Nuln Ironsiders using Ferlangen Boots

### ISSUE THREAD

**Issue by AmkoTheTerrible** [WarswordConquestTeam/Warsword-Conquest#27]
These floating men need to have their knees reinstalled so they stop flying around on levitation boots. 
Changes made to trp_nuln_ironsider (Nuln_Ironsider)
Item 1655 - Ferlangen_Boots (itm_ferlangen_boots1) removed
item 1668 - itm_ironsider_boots (Ironsider_Greaves) added
Edited troops.txt to change out ironsiders ferlangen boots for ironside greaves. 
[troops.txt](https://github.com/WarswordConquestTeam/Warsword-Conquest/files/4397807/troops.txt)

**Comment by WarswordConquestTeam** [comment]
changed
